% import MATPOWER
addpath( ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/lib', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/lib/t', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/data', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/most/lib', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/most/lib/t', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/mp-opt-model/lib', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/mp-opt-model/lib/t', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/mips/lib', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/mips/lib/t', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/mptest/lib', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/mptest/lib/t', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/extras/maxloadlim', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/extras/maxloadlim/tests', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/extras/maxloadlim/examples', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/extras/misc', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/extras/reduction', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/extras/sdp_pf', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/extras/se', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/extras/smartmarket', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/extras/state_estimator', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/extras/syngrid/lib', ...
    '/Users/michal/Documents/projects/FDR/matpower7.1/extras/syngrid/lib/t', ...
    '-end' );

% configuration
dead_band = 5;
config.x_c0_magnitude = 200;
config.N = 50;
config.problem = 'matpower';
config.alpha = 0.99;
config.k_max = 5000;
config.iter_max = 10;
config.deadband_size = dead_band;
config.deadband = true;
config.name = ['_matpower_', num2str(dead_band)];

% run the simulations and generate results
FDR_runner(config)


